receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors_allowed_origins:
        - "*"

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "HONEYCOMB-API-KEY-GOES-HERE"
      "x-honeycomb-dataset": "DATASET-NAME-GOES-HERE"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]